constants/creator_groups.json, constants/domain_groups.json, data_summaries/Pure-Dove.json, src/collection_mapper.py, src/downloaders.py, src/preparers.py
Hi @wwbrannon, 
I have added the initial draft of the Pure-Dove dataset. It would be great if you would kindly have a look and let me know if any changes are required.
Best,
Manan
=> Add Pure-Dove Dataset

data_summaries/Thai Gen AI (Dolly).json, src/collection_mapper.py, src/downloaders.py, src/preparers.py
All tests are passing. c.c @shayne-longpre
=> Add Thai Gen AI (Dolly) dataset

data_summaries/Thai Gen AI (GPTeacher).json, src/collection_mapper.py, src/downloaders.py, src/preparers.py
All tests are passing. c.c. @shayne-longpre
=> Add Thai Gen AI (GPTeacher) dataset

data_summaries/Thai Gen AI (Alpaca).json, src/collection_mapper.py, src/downloaders.py, src/preparers.py
All tests are passing. c.c @shayne-longpre
=> Add Thai Gen AI (Alpaca) dataset

constants/task_groups.json, data_summaries/EverythingLM.json
Hi @shayne-longpre @Muennighoff,
I have tried to address the following comments and the tests pass as well. Feel free to let me know if any other changes are required.
> - Could we retroactively add the OpenAI license/terms to the list of licenses
> - It looks like in HF they have a pie chart with a few more tasks we didn't include in the Task Categories. Any chance we could expand our list to make sure its covering all of there's?
Thanks,
Manan
=> Address comments - EverythingLM

constants/license_classes.json, constants/model_groups.json, data_summaries/Thai Gen AI (Alpaca).json
addressed all the comments @shayne-longpre -- all tests are passing.
=> Address comments -- Thai Gen AI (Alpaca) dataset

data_summaries/Thai Gen AI (Dolly).json
c.c @shayne-longpre and @wwbrannon. All tests are passing, feel free to merge if there are no other changes required. :)
=> Address comments -- "Thai Gen AI (Dolly)"

data_summaries/Thai Gen AI (GPTeacher).json
c.c @shayne-longpre and @wwbrannon. All tests are passing, feel free to merge if there are no other changes required. :)
=> Address comments -- Thai Gen AI (GPTeacher)"

src/downloaders.py
DialogStudio update & WizardLM datasets link fixed
=> Update downloaders.py with fixed dialogstudio and WizardLM links

src/downloaders.py
Dialogstudio fixed and tested using "python src/download_and_filter.py -c src/configs/pile_v2_test.yaml" command
=> Update downloaders.py fixed dialogstudio

src/downloaders.py
Finally, the code tested and fixed  together with dataset authors
=> Update downloaders.py to fix DialogStudio download issues

data_summaries/Feedback Collection.json, data_summaries/Preference Collection.json, src/collection_mapper.py, src/downloaders.py, src/preparers.py
@shayne-longpre 
I've updated the Feedback Collection (Prometheus 1) and added the Preference Collection (Prometheus 2) datasets!
Please let me know if there are any issues regarding this update, thanks in advance!
=> revise feedback collection and update preference collection

src/web_analysis/gpt_tos_analysis.py, src/web_analysis/requirements_gpt_tos_analysis.txt
=> fix(web_analysis): stream_json func + formatting fixes

src/web_analysis/gpt_tos_analysis.py
fix issue with date formatting when streaming json
=> fix(web_analysis): stream_json in gpt-4o annotations

src/analysis/market_analysis.ipynb
- The total tokens are shown as a percentage of the total everywhere instead of long numbers. No normalization to show the trend.
- Color palette from Figma for left plot, and neutral color for the right plot
- Tight layout to allow more space on the paper, with larger fonts to make it visible
- Font is times as decided on Slack
- Everything is parametrizable
=> Market Analysis v2

.env.template, README.md, requirements.txt, src/download_and_filter.py, src/downloaders.py, src/preparers.py
1. ChatDoctor requires keyword input instead of inputs
2. We are downloading toxigen_explanations.csv file for CobraFrames, it can not be downloaded via HF Hub due to columns mistach. Reading it directly via pandas
3. Feedback Collection: requires the split to be mentioned explicitly.
=> download_and_filter.py fix for datasets (ChatDoctor, Cobra Frames, Feedback Collection)

src/collection_mapper.py, src/downloaders.py, src/preparers.py
- Added Prepare Function for Open Platypus
- Added Open platypus in the collection_mappers
=> Add: Open Platypus

src/analysis/multimodal_analysis.ipynb, src/analysis/multimodal_util.py
@shayne-longpre I created a new PR as it was easier to resolve the existing merge conflicts. Many thanks for the feedback. If there is anything that needs to be updated, please feel free to add it here, and I can look into it.
=> Tasks charts update

src/preparers.py
=> add: Evol instruct Fix Preparers

src/analysis/multimodal_analysis.ipynb, src/analysis/multimodal_util.py
Not executed code with clear outputs in the multimodal notebook
=> Update multimodal analysis and utilities

data_summaries/Feedback Collection.json, data_summaries/Lumos Grounding.json, data_summaries/No Robots.json, data_summaries/Open-Platypus.json, data_summaries/PII-Masking-200k.json, data_summaries/Preference Collection.json, data_summaries/UltraChat_200k.json, data_summaries/WildChat.json
-Feedback Collection 
- PII-Masking-200k 
- Lumos Grounding 
- Preference Collection 
- WildChat  
- No Robots
Missing:
- MegaWika (RAM Issue)
- DialogStudio (Error)
=> add: new data summaries

src/analysis/multimodal_analysis.ipynb
Upgrade Time plot [Fig 2]: (1) Remove grid lines. (2) Show every second year on x-axis, e.g. “2024”, “2022”, “2020”, etc. (3) Increase font sizes slightly.
=> Update Fig 2 in multimodal analysis notebook

data_summaries/DialogStudio.json
=> add: dialog_studio

data_summaries-video/disney-videogeneration-dataset.json, data_summaries-video/finevideo.json, data_summaries-video/mvbench.json, data_summaries-video/openvid-1M.json, data_summaries-video/sharegpt4video.json, data_summaries-video/video-mme.json, data_summaries-video/vidprom.json
Added data summaries for the following video datasets:
- https://huggingface.co/datasets/HuggingFaceFV/finevideo
- https://huggingface.co/datasets/lmms-lab/Video-MME
- https://huggingface.co/datasets/Wild-Heart/Disney-VideoGeneration-Dataset
- https://huggingface.co/datasets/WenhaoWang/VidProM
- https://huggingface.co/datasets/nkp37/OpenVid-1M
- https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video
- https://huggingface.co/datasets/OpenGVLab/MVBench
=> added video data summaries

requirements.txt, src/download_and_filter.py, src/downloaders.py
- Remove Dataset restrictions from 2.15
- Updated stack-exchange-instruction from ArmelR/stack-exchange-instruction to DataProvenanceInitiative/stack-exchange-instruction-2split
=> Remove Datasets version restriction

src/analysis/README.md, src/analysis/aggregate.py, src/analysis/data/agents_counter/all_agents_counter.csv, src/analysis/market_analysis.ipynb, src/analysis/robots_analysis.ipynb, src/analysis/visualization_util.py, src/web_analysis/parse_robots.py, src/web_analysis/robots_util.py, src/web_analysis/test_robots.py
- Data is aggregated into streamlined format
- Clean up visualization_util
- Tests for robots parser
- README update
See README for full json structure, instructions to download, etc!
=> Feat: Aggregate Data
